# https://circleci.com/docs/2.0/configuration-reference/

version: 2.1

workflows:
  main:
    jobs:
      - syntax-check

jobs:
  syntax-check:
    docker:
      - image: hashicorp/terraform:0.12.24
    steps:
      - checkout
      - run:
          name: terraform syntax check
          command: |
            terraform init
            terraform validate

